default: &default
  adapter: postgresql
  encoding: unicode
  username: marko # Substituia pelo nome de usu치rio local, se aplic치vel
  password: # Substituia pela senha de usu치rio local, se aplic치vel
  host: localhost
  pool: 5

development:
  <<: *default
  database: ruby_db

test:
  <<: *default
  database: ruby_db_test


